# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/trouver',
                'doc_host': 'https://hyunjongkimmath.github.io',
                'git_url': 'https://github.com/hyunjongkimmath/trouver',
                'lib_path': 'trouver'},
  'syms': { 'trouver.core': {'trouver.core.foo': ('core.html#foo', 'trouver/core.py')},
            'trouver.helper': {'trouver.helper.find_regex_in_text': ('helper.html#find_regex_in_text', 'trouver/helper.py')}}}