name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/setup-python@v1  # Set up Python
        with:
          python-version: '3.10'
          architecture: 'x64'
      # Install system dependencies required for PyQt6
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx libegl1-mesa libxkbcommon-x11-0 libdbus-1-3
      # Use fastai's workflow for deploying to GitHub Pages
      - uses: fastai/workflows/quarto-ghp@master
