# name: CI
# on:  [workflow_dispatch, pull_request, push]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps: [uses: fastai/workflows/nbdev-ci@master]

# I am looking at this for how to update the python version.
# https://forums.fast.ai/t/python-version-error-while-running-ci-operations-in-github/98482/3

name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      # The following installation is for some packages needed by PyQt6
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx libegl1-mesa libxkbcommon-x11-0 libdbus-1-3
      - name: nbdev test step
        run: |
          ls
      - uses: fastai/workflows/nbdev-ci@master
        with:
            version: '3.10'
