name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Copies /nbs/_tests to the base directory of this workflow
      - name: Copy test files
        run: |
          cp -r "${GITHUB_WORKSPACE}/nbs/_tests" .
      - uses: fastai/workflows/nbdev-ci@master
